- hosts: "{{ contrato }}"
  gather_facts: false  # Desativamos a coleta de fatos para economizar tempo

  vars:
    Cliente_Helper: "helper-totem Setup 2.6.2.exe"
    installation_directory: "C:\\Helper"  # Defina o diretório de instalação aqui
    mongosh: "mongosh-2.0.1-x64.msi"
    ip: "172.16.30.249"  # Adicione o IP do Zabbix aqui
    ansible_winrm_operation_timeout_sec: 120
    ansible_winrm_read_timeout_sec: 180


  tasks:
    - name: Verificar se o processo HelperMonitor.exe está em execução
      win_shell: |
        Get-Process -Name "HelperMonitor" -ErrorAction SilentlyContinue
      register: process_check_result
      ignore_errors: yes

    - name: Encerrar o processo HelperMonitor.exe (se estiver em execução)
      win_shell: Stop-Process -Name "HelperMonitor" -Force -ErrorAction SilentlyContinue
      when: process_check_result.rc == 0  # Executar apenas se o processo estiver em execução
      ignore_errors: yes

    - name: Executar o instalador no Windows do MONGOSH
      win_shell: |
        Start-Process -Wait -FilePath "{{installation_directory}}\\{{mongosh}}"
      environment:
        PATH: "{{ansible_env.PATH}}"
      vars:
        ansible_shell_type: powershell

    - name: Atualiza o IP do Zabbix com o MongoDB Shell
      ansible.windows.win_shell: |
        $ip = "{{ ip }}"
        mongosh --quiet --eval "const db = connect('mongodb://localhost:27017/helper'); db.configs.updateOne({}, { `$set: { ipZabbix: '$ip'} });"
      args:
        executable: powershell

    - name: Encerrar o processo Cliente Helper
      win_shell: |
        Stop-Process -Name "Helper-Totem" -Force -ErrorAction SilentlyContinue
      ignore_errors: yes

    - name: Executar o instalador da nova versao Cliente Helper
      win_shell: |
        Start-Process -Wait -FilePath "{{installation_directory}}\\{{ Cliente_Helper }}"

# helper monitor contaminado#############
    - name: Iniciar o processo helpermonitor.exe
      win_shell: |
        Start-Process -Wait -FilePath "C:\Helper\Helper Monitor\HelperMonitor.exe"
      ignore_errors: yes
      async: 300
      poll: 0
      register: process_start_result
