- name: Acessar a pasta e descobrir a versão do programa Helper-Totem
  hosts: "{{ contrato }}"
  gather_facts: no  # Não coletar informações do sistema, pois não é necessário

  tasks:
    - name: Verificar a versão do programa Helper-Totem
      win_shell: |
        $ProgramPath = Join-Path -Path $env:LOCALAPPDATA -ChildPath "Programs\Helper-Totem\helper-totem.exe"
        (Get-Command $ProgramPath).FileVersionInfo.FileVersion
      register: helper_totem_version

    - name: Exibir a versão do programa Helper-Totem
      debug:
        var: helper_totem_version.stdout
