- name: Acessar a pasta e descobrir a vers達o do programa PROGRAMA-Sip-Ghost
  hosts: "{{ contrato }}"
  gather_facts: no

  tasks:
    - name: Verificar a vers達o do programa PROGRAMA-Sip-Ghost
      win_shell: |
        $ProgramPath = "C:\PROGRAMA\SIP\PROGRAMASIPClientGhost.exe"
        if (Test-Path $ProgramPath) {
          (Get-Command $ProgramPath).FileVersionInfo.FileVersion
        } else {
          Write-Host "O caminho do programa n達o foi encontrado."
        }
      register: PROGRAMAsipghost_version

    - name: Exibir a vers達o do programa PROGRAMA-Sip-Ghost
      debug:
        var: PROGRAMAsipghost_version.stdout